# ZSH ------------------------------------------------------------------------------
'.oh-my-zsh':
  type: archive
  url: 'https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: '168h'
  exclude:
    - '*/.*'
    - '*/templates'
    - '*/themes'

'.oh-my-zsh/custom/themes/powerlevel10k':
  type: archive
  url: 'https://github.com/romkatv/powerlevel10k/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: '168h'

'.oh-my-zsh/custom/plugins/zsh-syntax-highlighting':
  type: archive
  url: 'https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: '168h'
  exclude:
    - '*/.editorconfig*'
    - '*/.gitattributes'
    - '*/.github'
    - '*/.gitignore'

'.oh-my-zsh/custom/plugins/zsh-autosuggestions':
  type: archive
  url: 'https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: '168h'
  exclude:
    - '*/.editorconfig*'
    - '*/.gitattributes'
    - '*/.github'
    - '*/.gitignore'


# TMUX -----------------------------------------------------------------------------
'.config/tmux':
  type: archive
  url: 'https://github.com/gpakosz/.tmux/archive/master.tar.gz'
  #exact: true # Disable exact checking to allow for custom user configs
  stripComponents: 1
  refreshPeriod: '168h'
  exclude:
    - '*/.github'
    - '*/.gitignore'
    - '*/.gitattributes'
    - '*/.logo'
    - '*/.tmux.conf.local'

# Kitty ----------------------------------------------------------------------------
'.config/kitty/nord-kitty':
  type: archive
  url: 'https://github.com/connorholyday/nord-kitty/archive/master.tar.gz'
  exact: true
  stripComponents: 1
  refreshPeriod: '168h'
  exclude:
    - '*/screenshot.png'
