section: screens
	JeanYves-PC:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	Jeans-Macbook-Pro:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
    # MBP bottom center of 2x23" desktop screens
	JeanYves-PC:
		down(36,50) = Jeans-Macbook-Pro(0,43)
		down(50,64) = Jeans-Macbook-Pro(57,100)
	Jeans-Macbook-Pro:
        up(0,43) = JeanYves-PC(36,50)
        up(57,100) = JeanYves-PC(50,64)
end

section: options
	protocol = barrier
	relativeMouseMoves = false
	win32KeepForeground = false
	defaultLockToScreenState = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 512000
	switchCorners = none 
	switchCornerSize = 0
    mousebutton(4) = keystroke(meta+[,Jeans-Macbook-Pro)
    mousebutton(5) = keystroke(meta+],Jeans-Macbook-Pro)
end

